### ISSUE TITLE
MistralAI: Chat response leads to Exception in CreateResponse.php

### ISSUE THREAD

**Issue by dguembel-itomig** [theodo-group/LLPhant#286]
I am using llphant (well, trying to..) to access the API of Mistral with the following code. Executing it leads to an exception like the following one. 

It looks to me as if the structure of the response is different from what the OpenAI API PHP layer (used by MistralAIChat(?)) expects, maybe due to a change upstream in Mistral. 
Please let me know if I can be of any further assistance debugging this.

```
$config = new OpenAIConfig();
$config->apiKey = $this->apiKey;
$config->url = $this->url;
$config->model=$this->model;
$chat = new MistralAIChat($config);

$chat->setSystemMessage ($sSystemPrompt);
$response = $chat->generateText($sMessage);
```

......

```

Uncaught TypeError: array_map(): Argument #2 ($array) must be of type array, null given in /var/www/html/itop320pro/env-production/itomig-ai-base/vendor/openai-php/client/src/Responses/Chat/CreateResponse.php:50
Stack trace:
#0 /var/www/html/itop320pro/env-production/itomig-ai-base/vendor/openai-php/client/src/Responses/Chat/CreateResponse.php(50): array_map()
#1 /var/www/html/itop320pro/env-production/itomig-ai-base/vendor/openai-php/client/src/Resources/Chat.php(35): OpenAI\Responses\Chat\CreateResponse::from()
#2 /var/www/html/itop320pro/env-production/itomig-ai-base/vendor/theodo-group/llphant/src/Chat/OpenAIChat.php(352): OpenAI\Resources\Chat->create()
#3 /var/www/html/itop320pro/env-production/itomig-ai-base/vendor/theodo-group/llphant/src/Chat/OpenAIChat.php(197): LLPhant\Chat\OpenAIChat->generateResponseFromMessages()
#4 /var/www/html/itop320pro/env-production/itomig-ai-base/vendor/theodo-group/llphant/src/Chat/OpenAIChat.php(66): LLPhant\Chat\OpenAIChat->generate()
#5 /var/www/html/itop320pro/env-production/itomig-ai-base/src/Engine/MistralAIEngine.php(126): LLPhant\Chat\OpenAIChat->generateText()
...
```

**Comment by MaximeThoonsen** [comment]
hey @dguembel-itomig thanks for bringing up this bug!

**Comment by MaximeThoonsen** [comment]
hey @dguembel-itomig . The bug is fixed. Tell me if it is well working for you?

**Comment by dguembel-itomig** [comment]
Hi @MaximeThoonsen thank you, I made some tests and indeed it seems to work as expected now! :sunglasses:
